way_points: {
   table_two: {
      x: -1.645,
      y: -2.647,
      z: 0.0, 
      w:    0.937,
      wx: 0,
      wy: 0,
      wz:  0.348
    },
   table_one: {
      x: -2.45,
      y: -1.93,
      z: 0.0, 
      w:  0.485,
      wx: 0,
      wy: 0,
      wz:    0.875
    },
   table_three: {
      x: -1.344,
      y: -2.755,
      z: 0.0, 
      w:  0.897,
      wx: 0,
      wy: 0,
      wz:    -0.442
    },
   table_four: {
      x: -1.9,
      y: -2.4,
      z: 0.0, 
      w:  0.897,
      wx: 0,
      wy: 0,
      wz:    -0.442
    }
}
num_object: 0
